export const UI_DELAYS = {
  TOAST_DISPLAY: 2000,
  TOAST_FADE: 300,
  BUTTON_RESET: 1000,
  STREAM_CLEAR: 2000,
} as const;

export const UI_LIMITS = {
  PROMPT_TRUNCATE_LENGTH: 10000,
  MESSAGE_EXPAND_THRESHOLD: 300,
  CONVERSATION_HISTORY_DISPLAY: 5,
} as const;
