export const WORKFLOW_LIMITS = {
  MAX_STEP_TOKENS: 8000,
  MAX_TOTAL_HISTORY: 20000,
  MAX_CONVERSATION_DISPLAY: 3,
  RESPONSE_TRUNCATE_LENGTH: 2000,
  USER_INPUT_TRUNCATE_LENGTH: 500,
  HISTORY_RESPONSE_LENGTH: 1500,
} as const;

export const WORKFLOW_CACHE = {
  PROJECT_CONTEXT_TTL: 5 * 60 * 1000,
  MAX_TOKENS_PER_REQUEST: 50000,
} as const;
